### ISSUE TITLE
Running code for unseen video as a test data

### ISSUE THREAD

**Issue by FatemeBameri** [e-apostolidis/AC-SUM-GAN#3]
Hello

Thank you for sharing your code. That is very interesting. I could train your code well. But I do not know how do I run the AC-SUM-GAN model for unseen videos?
If there are some commands, please, share them with me.

best regards,

**Comment by e-apostolidis** [comment]
Hi there! Thank you for your interest in our method and sorry for the late response. To run a pretrained model on a new (unseen) video and create its summary is actually a multi-step process that requires: i) the segmentation of the video into shots (or sub-shots in the case of single-shot user-generated videos) and ii) the use of a method (e.g. the Knapsack algorithm) that selects the most important fragments (according to the automatically-made estimations by the model) and builds a summary of a pre-defined time budgets. For the time being, I have not available a set of scripts that implements this processing pipeline in an end-to-end manner. However, you can test a freely-available web service that integrates one of our previous summarization approaches. The web service (available at: http://multimedia2.iti.gr/videosummarization/service/start.html) lets you submit videos in various formats and generate summaries for use in various social media channels. I hope this helps!

**Comment by FatemeBameri** [comment]
Thank you so much for the useful explanation. I could train your code by generating h5 files for my own dataset by reading issues in Kaiyang Zhou Github pages.
